project('learn-cpp-the-hard-way', 'cpp', default_options: ['cpp_std=c++20'])
fmt = dependency('fmt')

executable('nl', 'nl.cpp', dependencies: fmt)
executable('cat', 'cat.cpp', dependencies: fmt)
executable('head', 'head.cpp', dependencies: fmt)
executable('tail', 'tail.cpp', dependencies: fmt)
executable('ls', 'ls.cpp', dependencies: fmt)
executable('cp', 'cp.cpp', dependencies: fmt)